Safe Time: 30            #Amount of seconds before players become "safe"
Chest Time: 45           #Amount of seconds before deathchests are open for everyone
DeathTP Time: 30         #Amount of seconds before players can teleport after death
PVPLogger Health: 50     #Health the PVP logger zombie has when it spawns
NameTag Color: 'c'       #Color that the nametag of unsafe people will be
DeathChest Enabled: true
DeathTP Enabled: true
Use TagAPI: true
Disable Flying: true     #Stops flight for those who aren't safe
Auto update: true        #Auto update the plugin from dev.bukkit.org
version: '1.2'           #Editing this might ruin the config. Sorry.