Tagging:
    Enabled: true             #Turns off making people unsafe
    NameTag Color: 'c'        #Color that the nametag of unsafe people will be
    Prevent Teleport: true    #Players who are tagged can/cannot teleport
    Remove Invisible: true    #Makes people who are unsafe visible
    Disable Enderpearls: true #Disables enderpearls for people who are unsafe
    Anti Pilejump: false      #Only the people who were PVPing in the unsafe zone can continue to pvp
    Disable Flying: true      #Stops flight for those who aren't safe
    Safe Time: 30
    Disabled Worlds: 'example1,example2'
    Use TagAPI: true
    Disabled Commands: 'warp,heal'
Death:
    DeathTP Enabled: true
    DeathTP Time: 30         #Amount of seconds before players can teleport after death
    DeathChest Enabled: true
    Chest Time: 45           #Amount of seconds before deathchests are open for everyone
PvPLogger Zombie:
    Enabled: true
    Keep Player Health: true #Set true to make the zombie spawn with the player's health
    Health: 50
Auto update: true            #Auto update the plugin from dev.bukkit.org
Send Usage: true             #Sends plugin usage statistics.
