name: PvPTag
version: 1.3
author: Tirelessly
main: com.github.cman85.PvPTag.PvPTag
softdepend: [TagAPI]
commands:
   csafe:
      description: Make a player safe from attack
      usage: /csafe <player>
      permission: pvptag.callsafe
   callsafe:
      description: Make a player safe from attack
      usage: /callsafe <player>
      permission: pvptag.callsafe
   chit:
      description: Make a player vulnerable to attack
      usage: /ch <player>
      permission: pvptag.callhit
   callhit:
      description: Make a player vulnerable to attack
      usage: /callhit <player>
      permission: pvptag.callhit
   pvptag:
      description: PvPTag's technical command
      usage: /pvptag <reload|setcolor <color>>
      permission: pvptag.pvptag